name: Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test ./tests

    - name: Build for linux
      run: mkdir linux && GOOS=linux GOARCH=amd64 go build -v -o linux/git-private .

    - name: Build for macintel
      run: mkdir macintel && GOOS=darwin GOARCH=amd64 go build -v -o macintel/git-private .

    - name: Build for macarm
      run: mkdir macarm && GOOS=darwin GOARCH=arm64 go build -v -o macarm/git-private .

    - name: Build for windows
      run: mkdir windows && GOOS=windows GOARCH=amd64 go build -v -o windows/git-private.exe .
